In [1]:
import numpy as np
import math as m

def cart2sph(x,y,z):
    XsqPlusYsq = x**2 + y**2
    r = m.sqrt(XsqPlusYsq + z**2)               # r
    elev = m.atan2(z,m.sqrt(XsqPlusYsq))     # theta
    az = m.atan2(y,x)                           # phi
    return r, elev, az

def cart2sphA(pts):
    return np.array([cart2sph(x,y,z) for x,y,z in pts])

def appendSpherical(xyz):
    np.hstack((xyz, cart2sphA(xyz)))

In [3]:
r,elev,az=cart2sph(2,2,3)
print (r)
print (elev)
print (az)

4.123105625617661
0.8148269163709889
0.7853981633974483


In [1]:
import numpy as np

xyz=np.array([[2,2,3]])

def appendSpherical_np(xyz):
    ptsnew = np.hstack((xyz, np.zeros(xyz.shape)))
    xy = xyz[:,0]**2 + xyz[:,1]**2
    r = np.sqrt(xy + xyz[:,2]**2)
    #ptsnew[:,4] = np.arctan2(np.sqrt(xy), xyz[:,2]) # for elevation angle defined from Z-axis down
    theta = np.arctan2(xyz[:,2], np.sqrt(xy)) # for elevation angle defined from XY-plane up
    phi = np.arctan2(xyz[:,1], xyz[:,0])
    
    cal=np.array([[r,theta,phi]])
    return cal

In [77]:
xyz.shape

(1, 3)

In [78]:
np.zeros(xyz.shape)

array([[0., 0., 0.]])

In [79]:
xyz[:,1]

array([2])

In [80]:
xyz[:,0]

array([2])

In [2]:
ptsnew=appendSpherical_np(xyz)
print(ptsnew)

[[[4.12310563]
  [0.81482692]
  [0.78539816]]]
